services:
  app:
    build: .
    image: kat-app
    ports:
      - 8080:8080
    container_name: app-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: PGPASSWORD
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PGPASSWORD
      POSTGRES_DB: kat
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db:
    driver: local